### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by keepAwayFrom404** [answershuto/VueDemo#3]
感觉这里可以优化一下
22行：set: function reactiveSetter (newVal) {
            if (newVal === val) return;
            val = newVal;
            cb(newVal);
        }

**Comment by answershuto** [comment]
@keepAwayFrom404  想要怎么样的优化呢？麻烦提个pr吧

**Comment by keepAwayFrom404** [comment]
就源码里面没有val = newVal;这一句 觉得可以加上
